Repository ethereum/py-evm, pull requests merged in 2018-12, with the labels that each got.

#1555 Rename data structures and constants
  eth/beacon/block_committees_info.py
  eth/beacon/enums/signature_domain.py
  eth/beacon/enums/special_record_types.py
  eth/beacon/enums/validator_registry_delta_flags.py
  eth/beacon/enums/validator_set_delta_flags.py
  eth/beacon/helpers.py
  eth/beacon/state_machines/configs.py
  eth/beacon/state_machines/forks/serenity/configs.py
  eth/beacon/types/attestation_data.py
  eth/beacon/types/attestation_records.py
  eth/beacon/types/deposit_parameters_records.py
  eth/beacon/types/fork_data.py
  eth/beacon/types/pending_attestation_records.py
  eth/beacon/types/shard_committees.py
  eth/beacon/types/states.py
  eth/beacon/types/validator_records.py
  tests/beacon/conftest.py
  tests/beacon/helpers.py
  tests/beacon/test_helpers.py
  tests/beacon/types/test_attestation_data.py
  tests/beacon/types/test_attestation_processed_attestation.py
  tests/beacon/types/test_attestation_signed_data.py
  tests/beacon/types/test_deposit_parameters_record.py
  tests/beacon/types/test_fork_data.py
  tests/beacon/types/test_pending_attestation_record.py
  tests/beacon/types/test_shard_and_committee.py
  tests/beacon/types/test_shard_committee.py
  tests/beacon/types/test_states.py
  tests/beacon/types/test_validator_record.py
  tests/trinity/core/p2p-proto/test_bcc.py
Labels: eth2.0

#1553 Use 99th percentile and standard deviation to dynamically tune peer timeout
  tests/trinity/core/utils/test_percentile.py
  tests/trinity/core/utils/test_standard_deviation.py
  trinity/protocol/common/managers.py
  trinity/protocol/common/trackers.py
  trinity/sync/full/constants.py
  trinity/utils/percentile.py
  trinity/utils/stddev.py
Labels: PR state: needs review, comp: trinity, effort: E1 hours

#1563 Rework helper functions - part 2
  eth/beacon/block_committees_info.py
  eth/beacon/helpers.py
  tests/beacon/conftest.py
  tests/beacon/helpers.py
  tests/beacon/test_helpers.py
Labels: eth2.0

#1633 `StateMachine` and `StateTransition` layout
  eth/beacon/state_machines/base.py
  eth/beacon/state_machines/configs.py
  eth/beacon/state_machines/forks/serenity/__init__.py
  eth/beacon/state_machines/forks/serenity/blocks.py
  eth/beacon/state_machines/forks/serenity/configs.py
  eth/beacon/state_machines/forks/serenity/operations.py
  eth/beacon/state_machines/forks/serenity/state_transitions.py
  eth/beacon/state_machines/forks/serenity/states.py
  eth/beacon/state_machines/state_transitions.py
  tests/beacon/conftest.py
  tests/beacon/state_machines/conftest.py
  tests/beacon/state_machines/test_demo.py
Labels: eth2.0

#1662 Move SpoofTransaction out of private namespace
  eth/_utils/spoof.py
  eth/estimators/gas.py
  eth/typing.py
  eth/vm/spoof.py
  tests/core/helpers.py
  trinity/rpc/modules/eth.py
Labels: TEMP: Migrate to Trinity Repo

#1640 Routine for processing deposits
  eth/_utils/bls.py
  eth/beacon/deposit_helpers.py
  eth/beacon/exceptions.py
  eth/beacon/helpers.py
  eth/beacon/types/deposit_input.py
  eth/beacon/types/states.py
  eth/beacon/types/validator_records.py
  tests/beacon/test_deposit_helpers.py
  tests/beacon/test_helpers.py
  tests/beacon/types/test_states.py
  tests/beacon/types/test_validator_record.py
Labels: PR state: needs review, eth2.0

#1677 Put validator balances into a separate list in the state
  eth/beacon/deposit_helpers.py
  eth/beacon/helpers.py
  eth/beacon/types/states.py
  eth/beacon/types/validator_records.py
  tests/beacon/conftest.py
  tests/beacon/helpers.py
  tests/beacon/test_deposit_helpers.py
  tests/beacon/test_helpers.py
  tests/beacon/types/test_states.py
  tests/beacon/types/test_validator_record.py
Labels: eth2.0

#1631 Attestation validation
  eth/beacon/state_machines/forks/serenity/__init__.py
  eth/beacon/state_machines/forks/serenity/operations.py
  eth/beacon/state_machines/forks/serenity/state_transitions.py
  eth/beacon/state_machines/forks/serenity/validation.py
  eth/beacon/state_machines/state_transitions.py
  eth/beacon/types/attestations.py
  tests/beacon/conftest.py
  tests/beacon/state_machines/test_attestation_validation.py
  tests/beacon/state_machines/test_demo.py
  tests/beacon/state_machines/test_serenity_operations.py
  tests/beacon/test_helpers.py
  tests/beacon/types/test_attestation.py
Labels: eth2.0

#1682 Update Constants as per updated eth2.0 spec
  eth/beacon/state_machines/configs.py
  eth/beacon/state_machines/forks/serenity/configs.py
  tests/beacon/conftest.py
  tests/beacon/state_machines/conftest.py
Labels: eth2.0

#1681 Add beacon chain related new type
  eth/_utils/bitfield.py
  eth/_utils/bls.py
  eth/beacon/aggregation.py
  eth/beacon/constants.py
  eth/beacon/deposit_helpers.py
  eth/beacon/helpers.py
  eth/beacon/state_machines/configs.py
  eth/beacon/state_machines/forks/serenity/configs.py
  eth/beacon/state_machines/validation.py
  eth/beacon/types/attestation_data.py
  eth/beacon/types/attestations.py
  eth/beacon/types/blocks.py
  eth/beacon/types/crosslink_records.py
  eth/beacon/types/deposit_data.py
  eth/beacon/types/deposit_input.py
  eth/beacon/types/exits.py
  eth/beacon/types/fork_data.py
  eth/beacon/types/pending_attestation_records.py
  eth/beacon/types/proposal_signed_data.py
  eth/beacon/types/proposer_slashings.py
  eth/beacon/types/shard_committees.py
  eth/beacon/types/shard_reassignment_records.py
  eth/beacon/types/slashable_vote_data.py
  eth/beacon/types/states.py
  eth/beacon/types/validator_records.py
  eth/beacon/types/validator_registry_delta_block.py
  eth/beacon/typing.py
  tests/beacon/conftest.py
Labels: eth2.0
