Repository ethereum/py-evm, pull requests merged in 2018-10, with the labels that each got.

#1311 [Draft] Add `GRPCServer` and `GRPCClient` with its deps
  p2p/libp2p_bridge/Makefile
  p2p/libp2p_bridge/config.py
  p2p/libp2p_bridge/constants.py
  p2p/libp2p_bridge/docs/README.md
  p2p/libp2p_bridge/docs/images/python_go_structure.png
  p2p/libp2p_bridge/grpc_client.py
  p2p/libp2p_bridge/grpc_server.py
  p2p/libp2p_bridge/message.py
  p2p/libp2p_bridge/pb/event/event_pb2.py
  p2p/libp2p_bridge/pb/event/event_pb2_grpc.py
  p2p/libp2p_bridge/pb/message/message_pb2.py
  p2p/libp2p_bridge/pb/rpc/rpc_pb2.py
  p2p/libp2p_bridge/pb/rpc/rpc_pb2_grpc.py
  p2p/libp2p_bridge/test_grpc.py
  setup.py
  tests/p2p/libp2p_bridge/test_grpc_server.py
  tests/p2p/libp2p_bridge/test_message.py
  tox.ini
Labels: eth2.0

#1382 Remove obsolete hack
  p2p/peer.py
Labels: PR state: blocked

#1438 Fix warnings when printing Trinity cli header
  trinity/main.py
Labels: PR state: needs review, type: bug

#1437 Update to use f-strings
  trinity/__init__.py
  trinity/cli_parser.py
  trinity/config.py
  trinity/extensibility/plugin.py
  trinity/initialization.py
  trinity/main.py
  trinity/plugins/builtin/tx_pool/pool.py
  trinity/protocol/common/handlers.py
  trinity/protocol/common/managers.py
  trinity/protocol/common/validators.py
  trinity/protocol/eth/peer.py
  trinity/protocol/eth/validators.py
  trinity/protocol/les/peer.py
  trinity/protocol/les/proto.py
  trinity/sync/light/service.py
  trinity/tools/async_process_runner.py
  trinity/utils/chains.py
  trinity/utils/headers.py
  trinity/utils/log_messages.py
  trinity/utils/logging.py
  trinity/utils/version.py
Labels: PR state: needs review, type: refactor

#1436 move light-peer-chain tests
  .circleci/config.yml
  tests/trinity/core/chains/test_light_peer_chain.py
Labels: PR state: needs review, type: refactor

#1434 Fix mainnet genesis configuration
  docs/guides/eth/understanding_the_mining_process.rst
  eth/chains/mainnet/__init__.py
  eth/constants.py
  scripts/benchmark/utils/chain_plumbing.py
  tests/conftest.py
  tests/core/chain-object/test_gas_estimation.py
  tests/trinity/core/json-rpc/test_ipc.py
  tests/trinity/core/p2p-proto/test_sync.py
Labels: type: bug

#1433 Move mainnet DAO fork config into mainnet configuration
  eth/chains/mainnet/__init__.py
  eth/chains/mainnet/constants.py
  eth/chains/tester/__init__.py
  eth/tools/builder/chain/builders.py
  eth/tools/fixtures/helpers.py
  eth/vm/forks/homestead/__init__.py
  eth/vm/forks/homestead/headers.py
  tests/core/chain-object/test_chain_reorganization.py
  tests/core/tester/test_generate_vm_configuration.py
  tests/trinity/json-fixtures-over-rpc/test_rpc_fixtures.py
  trinity/protocol/common/boot.py
Labels: PR state: needs review, type: refactor
