Repository ethereum/py-evm, pull requests merged in 2018-02, with the labels that each got.

#363 Use the latest eth-utils
  setup.py
Labels: Needs Review, Sharding

#359 Relegate chaindb access to independent process
  evm/db/chain.py
  tests/trinity/database/test_chaindb_over_ipc.py
  tests/trinity/database/test_core_db_over_ipc.py
  tests/trinity/database/test_db_over_mp_connection.py
  trinity/README.md
  trinity/chains/__init__.py
  trinity/db/chaindb.py
  trinity/db/core.py
  trinity/db/pipe.py
  trinity/main.py
  trinity/utils/ipc.py
  trinity/utils/mp.py
Labels: Needs Review, Trinity

#347 Add paygas test cases
  evm/opcode_values.py
  tests/core/contract_fixtures/CREATE2_contract.py
  tests/core/contract_fixtures/CREATE2_contracts.json
  tests/core/contract_fixtures/PAYGAS_contract.py
  tests/core/contract_fixtures/PAYGAS_contracts.json
  tests/core/contract_fixtures/contract_fixture_compile_script.py
  tests/core/fixtures.py
  tests/core/vm/contract_fixture.py
  tests/core/vm/test_PAYGAS_tx_fee.py
  tests/core/vm/test_shard_vm.py
Labels: Sharding

#348 Remove validation code
  evm/rlp/headers.py
  evm/utils/numeric.py
  evm/vm/forks/sharding/contracts/validator_manager.json
  evm/vm/forks/sharding/contracts/validator_manager.v.py
  evm/vm/forks/sharding/vmc_handler.py
  tests/core/numeric-utils/test_int_to_bytes32.py
  tests/sharding/test_collation_header.py
  tests/sharding/test_vmc_handler.py
Labels: Needs Review, Sharding

#315 Add VM function to execute raw bytecode
  evm/vm/base.py
  evm/vm_state.py
  tests/json-fixtures/test_virtual_machine.py
Labels: Work in progress

#366 Add transaction-context object
  evm/computation.py
  evm/logic/call.py
  evm/logic/context.py
  evm/logic/system.py
  evm/transaction_context.py
  evm/vm/forks/frontier/computation.py
  evm/vm/forks/frontier/transaction_context.py
  evm/vm/forks/frontier/vm_state.py
  evm/vm/forks/sharding/computation.py
  evm/vm/forks/sharding/transaction_context.py
  evm/vm/forks/sharding/vm_state.py
  evm/vm/forks/spurious_dragon/utils.py
  evm/vm/message.py
  evm/vm_state.py
  tests/auxiliary/user-account/test_contract.py
  tests/core/message-object/test_message_object.py
  tests/core/vm/test_base_computation.py
  tests/core/vm/test_frontier_computation.py
  tests/json-fixtures/test_state.py
  tests/json-fixtures/test_virtual_machine.py
Labels: Ready for merge

#372 Some clean up for sharding
  evm/chains/chain.py
  evm/db/chain.py
  evm/utils/state.py
  evm/validation.py
  evm/vm/base.py
  evm/vm_state.py
  tests/core/chain-object/conftest.py
  tests/core/chain-object/test_chain.py
  tests/core/fixtures.py
  tests/core/vm/conftest.py
  tests/core/vm/test_vm.py
  tests/core/vm/test_vm_state.py
Labels: Needs Review

#365 Use chaindb over multiprocessing Manager for lightchain access to ChainDB
  evm/p2p/lightchain.py
  evm/p2p/test_peer.py
  tests/trinity/database/test_chaindb_over_ipc.py
  tests/trinity/database/test_core_db_over_ipc.py
  tests/trinity/database/test_database_over_ipc_manager.py
  trinity/README.md
  trinity/chains/__init__.py
  trinity/db/base.py
  trinity/db/chain.py
  trinity/db/chaindb.py
  trinity/db/core.py
  trinity/main.py
  trinity/utils/ipc.py
Labels: Needs Review, Trinity

#379 Initial Trinity Implementation
  .travis.yml
  evm/p2p/lightchain.py
  evm/p2p/test_peer.py
  setup.py
  tests/trinity/chain-management/test_initialize_data_dir.py
  tests/trinity/chain-management/test_initialize_database.py
  tests/trinity/chain-management/test_is_data_dir_initialized.py
  tests/trinity/chain-management/test_is_database_initialized.py
  tests/trinity/chains-utils/test_chain_config_object.py
  tests/trinity/cli/test_trinity_repl.py
  tests/trinity/conftest.py
  tests/trinity/database/test_database_over_ipc_manager.py
  tests/trinity/filesystem-utils/test_is_same_path.py
  tests/trinity/filesystem-utils/test_is_under_path.py
  tox.ini
  trinity/README.md
  trinity/__init__.py
  trinity/__version__.py
  trinity/chains/__init__.py
  trinity/chains/ropsten.py
  trinity/cli.py
  trinity/constants.py
  trinity/db/__init__.py
  trinity/db/base.py
  trinity/db/chain.py
  trinity/main.py
  trinity/utils/__init__.py
  trinity/utils/chains.py
  trinity/utils/db.py
  trinity/utils/filesystem.py
  trinity/utils/ipc.py
  trinity/utils/logging.py
  trinity/utils/mp.py
  trinity/utils/xdg.py
Labels: Needs Review, Trinity

#345 Implement CancelToken and use it everywhere
  evm/lightchain_shell.py
  evm/p2p/cancel_token.py
  evm/p2p/discovery.py
  evm/p2p/exceptions.py
  evm/p2p/lightchain.py
  evm/p2p/peer.py
  evm/p2p/state.py
  evm/p2p/test_cancel_token.py
  trinity/cli.py
  trinity/main.py
Labels: Needs Review

#396 Fix sharding branch after rebasing
  evm/db/chain.py
  evm/utils/address.py
  evm/utils/state_access_restriction.py
  evm/vm/forks/sharding/computation.py
  evm/vm/forks/sharding/vm_state.py
  setup.py
  tests/auxiliary/user-account/test_contract.py
  tests/core/access-restrictions-utils/test_access_list.py
  tests/core/helpers.py
  tests/core/vm/test_PAYGAS_tx_fee.py
  tests/core/vm/test_nonce_abstraction.py
  tests/core/vm/test_shard_vm.py
  tests/database/test_account_state_db.py
  tests/sharding/test_log_handler.py
  tests/sharding/test_vmc_handler.py
  tox.ini
Labels: Needs Review, Sharding

#393 Fix fallout from trinity changes
  evm/chains/chain.py
  evm/db/chain.py
  evm/lightchain_shell.py
  p2p/lightchain.py
  p2p/peer.py
  tests/p2p/integration_test_helpers.py
  tests/p2p/peer_helpers.py
  tests/p2p/test_lightchain.py
  tests/p2p/test_lightchain_integration.py
  trinity/cli.py
  trinity/db/chain.py
  trinity/main.py
Labels: Needs Review

#402 Trinity: move argparse parser to own module
  trinity/cli_parser.py
  trinity/main.py
Labels: Trinity

#409 Make mypy check bodies of untyped functions as well
  p2p/cancel_token.py
  p2p/discovery.py
  p2p/ecies.py
  p2p/kademlia.py
  p2p/les.py
  p2p/lightchain.py
  p2p/p2p_proto.py
  p2p/peer.py
  p2p/protocol.py
  p2p/state.py
  tests/p2p/test_cancel_token.py
  tox.ini
  trinity/cli.py
  trinity/rpc/main.py
  trinity/utils/logging.py
Labels: Needs Review

#350 JSON test builder
  evm/constants.py
  evm/db/chain.py
  evm/rlp/collations.py
  evm/rlp/headers.py
  evm/tools/test_builder/README.md
  evm/tools/test_builder/__init__.py
  evm/tools/test_builder/builder_utils.py
  evm/tools/test_builder/formatters.py
  evm/tools/test_builder/normalization.py
  evm/tools/test_builder/test_builder.py
  evm/utils/fixture_tests.py
  evm/vm/base.py
  evm/vm/execution_context.py
  evm/vm/forks/sharding/__init__.py
  evm/vm/forks/sharding/collations.py
  evm/vm/forks/sharding/vm_state.py
  tests/auxiliary/user-account/test_contract.py
  tests/core/vm/test_vm_state.py
  tests/fillers/__init__.py
  tests/fillers/build_json.py
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasAfterCall.json
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasFailBefore.json
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasFailThereafter.json
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasInCall.json
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasInsufficientBalance.json
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasNormal.json
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasOmitted.json
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasRepeated.json
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasRepeatedSameGasprice.json
  tests/fillers/json/fillers/GeneralStateTestFiller/stPaygas/PaygasZeroGasprice.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasAfterCall.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasFailBefore.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasFailThereafter.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasInCall.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasInsufficientBalance.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasNormal.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasOmitted.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasRepeated.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasRepeatedSameGasprice.json
  tests/fillers/json/tests/GeneralStateTests/stPaygas/PaygasZeroGasprice.json
  tests/fillers/vm_fillers/__init__.py
  tests/fillers/vm_fillers/paygas_fillers.py
  tests/json-fixtures/test_state.py
  tests/json-fixtures/test_virtual_machine.py
Labels: Needs Review, Sharding
