Repository ethereum/py-evm, pull requests merged in 2019-01, with the labels that each got.

#1679 Update StateMachine.__init__() and add `BeaconBlock`
  eth/beacon/db/chain.py
  eth/beacon/state_machines/base.py
  eth/beacon/state_machines/forks/serenity/blocks.py
  eth/beacon/types/blocks.py
  tests/beacon/conftest.py
  tests/beacon/db/test_beacon_chaindb.py
  tests/beacon/state_machines/forks/test_serenity_operations.py
  tests/beacon/state_machines/test_demo.py
  tests/beacon/state_machines/test_proposer_signature_validation.py
  tests/beacon/test_helpers.py
  tests/beacon/types/test_block.py
Labels: eth2.0

#1675 Add proof of custody placeholders
  eth/beacon/deposit_helpers.py
  eth/beacon/helpers.py
  eth/beacon/types/attestation_data_and_custody_bits.py
  eth/beacon/types/blocks.py
  eth/beacon/types/custody_challenges.py
  eth/beacon/types/custody_reseeds.py
  eth/beacon/types/custody_responses.py
  eth/beacon/types/deposit_input.py
  eth/beacon/types/pending_attestation_records.py
  eth/beacon/types/slashable_vote_data.py
  eth/beacon/types/states.py
  eth/beacon/types/validator_records.py
  tests/beacon/conftest.py
  tests/beacon/helpers.py
  tests/beacon/test_deposit_helpers.py
  tests/beacon/test_helpers.py
  tests/beacon/types/test_attestation_data_and_custody_bit.py
  tests/beacon/types/test_block.py
  tests/beacon/types/test_casper_slashings.py
  tests/beacon/types/test_slashable_vote_data.py
  tests/beacon/types/test_validator_record.py
Labels: PR state: needs review, eth2.0

#1698 Implement fast integer square root
  eth/_utils/numeric.py
Labels: eth2.0

#1695 Sync `get_block_root` and `get_shard_committees_at_slot ` and fix `test_demo`
  eth/beacon/helpers.py
  eth/beacon/state_machines/forks/serenity/operations.py
  eth/beacon/state_machines/forks/serenity/validation.py
  tests/beacon/state_machines/forks/test_serenity_operations.py
  tests/beacon/state_machines/test_demo.py
  tests/beacon/test_helpers.py
Labels: eth2.0

#1689 Add `get_merkle_root`
  eth/_utils/blobs.py
  eth/_utils/merkle.py
  eth/beacon/_utils/hash.py
  tests/core/merkle-utils/test_merkle_trees.py
Labels: eth2.0

#1700 Sync ethereum/eth2.0-specs#374 part1: types, constants, deposit_helpers
  eth/beacon/constants.py
  eth/beacon/deposit_helpers.py
  eth/beacon/enums.py
  eth/beacon/exceptions.py
  eth/beacon/helpers.py
  eth/beacon/state_machines/configs.py
  eth/beacon/state_machines/forks/serenity/configs.py
  eth/beacon/types/deposit_data.py
  eth/beacon/types/states.py
  eth/beacon/types/validator_records.py
  eth/beacon/types/validator_registry_delta_block.py
  tests/beacon/conftest.py
  tests/beacon/helpers.py
  tests/beacon/state_machines/conftest.py
  tests/beacon/state_machines/test_proposer_signature_validation.py
  tests/beacon/test_deposit_helpers.py
  tests/beacon/test_helpers.py
  tests/beacon/types/test_deposit_data.py
  tests/beacon/types/test_states.py
  tests/beacon/types/test_validator_record.py
  tests/beacon/types/test_validator_registry_delta_block.py
Labels: eth2.0

#1685 Add some more tests for Rewards
  tests/core/vm/test_rewards.py
Labels: PR state: needs review
